### ISSUE TITLE
Convert i3d_nonlocal_8x8_IN_pretrain_400k

### ISSUE THREAD

**Issue by ShiroKL** [Tushar-N/pytorch-resnet3d#10]
Hi,

I was wondering if it is possible with your code to convert i3d_nonlocal_8x8_IN_pretrain_400k model and the c2d model from the facebook repository ? 

EDIT : The conversion "works" there is no error during the conversion but I can not check if the performance are the same because I do not have the kinetics dataset.

**Comment by Tushar-N** [comment]
I've hard-coded params for the two models, so it likely won't work. You'd need to adjust the parameters or write a more general version of the conversion/model scripts.

**Comment by ruiyan1995** [comment]
> Hi,
> 
> I was wondering if it is possible with your code to convert i3d_nonlocal_8x8_IN_pretrain_400k model and the c2d model from the facebook repository ?
> 
> EDIT : The conversion "works" there is no error during the conversion but I can not check if the performance are the same because I do not have the kinetics dataset.

Did you have convert c2d model from caffe to pytorch?

**Comment by ruiyan1995** [comment]
@ShiroKL Did you have convert c2d model from caffe to pytorch?
