### ISSUE TITLE
Maxpool

### ISSUE THREAD

**Issue by wr0112358** [Tushar-N/pytorch-resnet3d#13]
The original implementation and the paper apply maxpooling in the nonlocal block after phi- and g-layers. In this implementation the maxpool is applied before them. Is this on purpose, does it affect the accuracy?

**Comment by Tushar-N** [comment]
The paper does say after, but the original implementation has it [before](https://github.com/facebookresearch/video-nonlocal-net/blob/c253ed5eb004fa2cae0490ed46f5018a3c3b060f/lib/models/nonlocal_helper.py#L37).
