### ISSUE TITLE
pkl file not found

### ISSUE THREAD

**Issue by DungVo1507** [Tushar-N/pytorch-resnet3d#15]
Hi @Tushar-N,
I'm so glad I found your awesome repo.
Sorry, I'm a newbie in this field so I'm having a hard time doing it.
I can't find 2 files `https://dl.fbaipublicfiles.com/video-nonlocal/i3d_baseline_32x2_IN_pretrain_400k.pkl` and `https://dl.fbaipublicfiles.com/video-nonlocal/i3d_nonlocal_32x2_IN_pretrain_400k.pkl.`
Can you send me these 2 files?
Thank you very much!

**Comment by Tushar-N** [comment]
Both these links seem accessible to me. Did a simple`wget https://dl.fbaipublicfiles.com/video-nonlocal/i3d_baseline_32x2_IN_pretrain_400k.pkl` not work?

Also disclaimer: This repo is dated. You'd probably be better off using [pytorchvideo](https://pytorchvideo.org/).
