### ISSUE TITLE
Extracting I3D features on a new dataset

### ISSUE THREAD

**Issue by DungVo1507** [Tushar-N/pytorch-resnet3d#16]
Hi, thanks for your help in advance.

I'm in dire need of I3D feature extraction on our dataset but I really don't know how to start from your repo.
Can you guide me step by step to implement it on our dataset?

Sorry I am new in this field,
Thank you so much!

**Comment by Tushar-N** [comment]
Look at this [issue](https://github.com/Tushar-N/pytorch-resnet3d/issues/12) for more details.
Alternately, use other tools:
- pretrained models from [pytorchvideo](https://pytorchvideo.org/docs/tutorial_torchhub_inference)
- Repos dedicated to feature extraction (e.g. [this one](https://github.com/antoine77340/video_feature_extractor))
