### ISSUE TITLE
10-crops I3D feature extraction

### ISSUE THREAD

**Issue by DungVo1507** [Tushar-N/pytorch-resnet3d#17]
Hi @Tushar-N 
Can you show me in detail how you 10-crops argumentation from an input video? Something like converting the video to a frame, then 10-crops argumentation,...
Sorry, I'm new in this field so I'm still having a lot of trouble.
Thank you very much!

**Comment by ro1406** [comment]
Hi @DungVo1507, did you manage to figure out how to do 10crop augmentation from the features extracted? If so, could you let me know too? Thanks :)

**Comment by DungVo1507** [comment]
@ro1406, all you need is [here](https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet)

**Comment by wzy1845** [comment]
> @ro1406, all you need is [here](https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet)

Thank you for your code! I ran the code very smoothly, but it did not achieve the expected effect after the run of feature extraction using [this repo](https://github.com/GowthamGottimukkala/I3D_Feature_Extraction_resnet). The result of the SH dataset was only less than 70%. My reproduction steps are as follows:

1.Use your code to extract i3D features
2.Run Make_list_SH.py in RTFM
3.Train and test RTFM
Are there any steps I miss? thank you for your time
