### ISSUE TITLE
maxpoo1 and maxpool2 inconsistent with the original paper

### ISSUE THREAD

**Issue by xwsgithub** [Tushar-N/pytorch-resnet3d#18]
hello! 
I found that the implementation of maxpool1 and maxpool2 is somewhat inconsistent with the original paper. The original size of maxpool1 is 3, 3, 3, while in this code it is 2, 3, 3. What is the purpose of this modification?

**Comment by Tushar-N** [comment]
Please use [pytorchvideo](https://github.com/facebookresearch/pytorchvideo).
