### ISSUE TITLE
/usr/bin/python3: Error while finding module specification for 'utils.convert_weights' (ModuleNotFoundError: No module named 'utils')

### ISSUE THREAD

**Issue by Madhav-Rao-1612** [Tushar-N/pytorch-resnet3d#19]
Hi Tushar-N, while converting caffe2 to pytorch , i am facing the issue
/usr/bin/python3: Error while finding module specification for 'utils.convert_weights' (ModuleNotFoundError: No module named 'utils')
i hope you could help me in this

**Comment by Tushar-N** [comment]
Not sure why this happens. The module is [here](https://github.com/Tushar-N/pytorch-resnet3d/blob/master/utils/convert_weights.py). 
Also this repo is deprecated. Please use [pytorchvideo](https://github.com/facebookresearch/pytorchvideo).
