### ISSUE TITLE
Accuracy only 53.2%!

### ISSUE THREAD

**Issue by HaiyiMei** [Tushar-N/pytorch-resnet3d#3]
Hi there, great job! I've got a problem here. I followed your instructions exactly how they were, but I just got a result that accuracy is 53.2%. Do you have any idea why it is so? Thanks!

**Comment by HaiyiMei** [comment]
By the way, it is the clip mode that got this accuracy.

**Comment by Tushar-N** [comment]
Are you running exactly the same pytorch/python versions? (1.0 and 3.7)?

**Comment by HaiyiMei** [comment]
> Are you running exactly the same pytorch/python versions? (1.0 and 3.7)?

I'm running in pytorch/python (1.1.0 and 3.6.8). 
I'll test in pytorch1.0 later. Thanks!

**Comment by HaiyiMei** [comment]
> Are you running exactly the same pytorch/python versions? (1.0 and 3.7)?

I've switched to torch1.0.0 / torchvision0.2.2 / python3.7.3. Here's the result:

(test) A: 0.532 | clf: 2.435 | total_loss: 2.435

Still not work.

**Comment by Tushar-N** [comment]
Did all the kinetics videos get downloaded and frames extracted properly?
I have ~18434 videos in the validation set for which I reported the numbers. Also, for reference, here's a [link](https://drive.google.com/file/d/1KkO6R_FlFbogTUdtMX_KyPCUNMh0Jwor/view?usp=sharing) to my exact model weights after conversion (in case something went wrong). Could you run eval.py with this file, just in case the conversion went wrong?

**Comment by HaiyiMei** [comment]
I've got 18310 videos in validation set, and with your weights I only got 50%( torch1.0.0 / torchvision0.2.2 / python3.7.3 / CUDA 9.0). It is driving me crazy, I can't find anything wrong.

I'm thinking if it is the preprocessing part that makes the difference? Have you ever modified the dataloader or transforms?

Plus, every time I run the code in video mode, the program will be killed before the first forward step for the network. And I got this error below. Why is this happening? 
`RuntimeError: DataLoader worker (pid 18644) is killed by signal: Bus error.

**Comment by Tushar-N** [comment]
I have exactly the same environment as you, I'm really not sure what's going on. I'll get some other people to test this and report if they get similar mismatches. Until then, my only other guess is that the videos were not burst to frames in the same way? I used the command from the official activitynet crawler ([link](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/download.py#L100)) to do this (ffmpeg 4.0.2).

> Plus, every time I run the code in video mode, the program will be killed before the first forward step for the network.

Is this just a memory error? With a batch size of 8, this takes up ~8GB GPU memory. 

Finally, another recent repo, [mmaction](https://github.com/open-mmlab/mmaction), provides pytorch kinetics pretrained I3D models, so you may want to take a look at that too.

**Comment by HaiyiMei** [comment]
Hey! I figured it out!
It is because of the function [glob.glob()](https://github.com/Tushar-N/pytorch-resnet3d/blob/e997fc6a4a632502460aece5e83e0bd2fd6206d9/data/kinetics.py#L24). After glob function, the frames should be sorted like: `frames.sort()`. Otherwise, the frames would be shuffled(or in system file binary order or something), not in time sorted.

After adding the sort step, my valid in r50_nl model came to P1: 0.660 | P5: 0.858 in clip mode. Thank you so much! Thanks for your great job and patient answering!

**Comment by Tushar-N** [comment]
Great catch! This completely slipped past me since I got lucky, and the files happened to be sorted when I ran it. Thanks for pointing it out, and sorry for the headache it caused!
